### ISSUE TITLE
Apply unmock for test builds only

### ISSUE THREAD

**Issue by stari4ek** [bjoernQ/unmock-plugin#17]
Unmock takes a lot of time if rebuild is invoked for main/debug build.
Currently I've added mock section to the root of app/build.gradle. Probably it can be solved with properly configured task dependencies and filtering, but it's better to have example somewhere around

**Comment by stari4ek** [comment]
hmm. probably this is different issue. Right now It performs rebuild pretty fast, but sometime I see long living "unMock" task in gradle console and overall time for rebuild is increased ~2min

**Comment by bjoernQ** [comment]
The actual "unmocking" is quite fast. I think the long delay is caused by redownloading the android.jar.

Currently the plugin downloads the JAR to the temp-dir - some systems purge the temp folder on reboots.

Now if you do a clean build it needs to redownload the JAR file first. That might take a while.

You can configure the "downloadTo" path to another directory that is not purged regularly - that should make things faster. (On clean builds or if the build file is changed it still needs to process that JAR again but that should be fast enough.)

Maybe you can try this and see if it works for you.

**Comment by stari4ek** [comment]
Yes. This is download speed issue. When I switched "downloadTo" I can see how slowly file grows.
BTW, configuration doesn't like path relative to home folder (_~/tmp_). Is it possible to set local file instead of "downloadFrom"?

**Comment by bjoernQ** [comment]
Never tried it but it should be possible to use an URL like "file:///path/file" to use a local file instead of a file downloaded from the internet.

Let me know if it works for you - otherwise this would be a nice feature to add.

**Comment by stari4ek** [comment]
file:// trick works well!
The only problem how to be in-sync if unMock will move to newer version.

**Comment by bjoernQ** [comment]
That's awesome - nice it works for you.

No need to worry about newer versions - the JAR is just a copy of the android.jar - there is no need to match that version to the UnMock version - it's more important to loosely match a supported Android version of you app.

So this is a perfect solution for situations like these - I should add a hint about the "file:///" thing in the README.md

**Comment by nekdenis** [comment]
thanks for plugin! 

Why not store downloaded jar in permanent dir that will not be cleared after reboot?

**Comment by bjoernQ** [comment]
You can specify your own target directory for the download.

See https://github.com/bjoernQ/unmock-plugin/issues/15

i.e. you can choose a directory that doesn't get cleared automatically

**Comment by bjoernQ** [comment]
Updated README.md to include this information.
