### ISSUE TITLE
Release tags

### ISSUE THREAD

**Issue by johnjohndoe** [bjoernQ/unmock-plugin#19]
Please maintain consistent releases by also adding Git tags and pushing them to this repository.

``` bash
$ git checkout {some-release-commit}
$ git tag -a "v.1.0.0" -m "Short summary of the release."
$ git push --tags origin master
```

Please consider using [semantic versioning](http://semver.org/) for release tags.

**Comment by bjoernQ** [comment]
Thanks for the hint. Actually I started with tagging but for some reason stopped it. 0.4.0 is tagged and hopefully I won't forget to tag the next releases.I don't think it makes sense trying to tag the releases between 0.1.1 and 0.4.0 (which are missing the tags) since it's possible to tag the wrong commit - which would be worse than having no tag.

Regarding semantic versioning: Good point - I shuld switch to a meaningful versioning scheme.

Thanks

**Comment by johnjohndoe** [comment]
> ... since it's possible to tag the wrong commit ...

Just checkout the commit where you published the release and increased the version number.

**Comment by bjoernQ** [comment]
All releases should be tagged now.

**Comment by johnjohndoe** [comment]
LGTM. Thanks :smiley_cat:
