### ISSUE TITLE
Missing support of Float and Double?

### ISSUE THREAD

**Issue by rekire** [bjoernQ/unmock-plugin#20]
Hi Björn,

I guess I found a bug. I have an internal native call which returns a float. I found via decompiling this code:

    public static long nativeReadLong(long var0) {
        return ABridge.callLong("android.os.Parcel.nativeReadLong(long)", (Object)null, new Object[]{new Long(var0)});
    }

    public static float nativeReadFloat(long var0) {
        return ((Float)ABridge.callObject("android.os.Parcel.nativeReadFloat(long)", (Object)null, new Object[]{new Long(var0)})).floatValue();
    }

    public static double nativeReadDouble(long var0) {
        return ((Double)ABridge.callObject("android.os.Parcel.nativeReadDouble(long)", (Object)null, new Object[]{new Long(var0)})).doubleValue();
    }

    public static String nativeReadString(long var0) {
        return (String)ABridge.callObject("android.os.Parcel.nativeReadString(long)", (Object)null, new Object[]{new Long(var0)});
    }

As you see for `Long` and `String` the code looks fine just for `double` and `float` will happen there some unboxing which causes the NPE. I guess that `ABridge` is missing the support for float and double, could you check it and confirm if this is a bug?

**Comment by bjoernQ** [comment]
In theory there shouldn't be a NPE in ABridge since the parameter passed in is a primitive float (which can't be NULL). Also there is no mention of ABridge in the stack trace which should be there in that case.

Maybe you can post the full code (including MyParcelable and all the mocking - i.e. a full compiling test case including your UnMock config clause) which should help tracking this  issue down. But it really seems to be no problem in UnMock.

**Comment by rekire** [comment]
Here is my stripped down demo project: https://github.com/rekire/ParcelableUnitTest

**Comment by bjoernQ** [comment]
Ok the problem with your test is you mock callBoolean - but it's actually callObject which is invoked.
The test still isn't green then since all the other reads won't return what is expected by test.

Attached a patch file here for your test (with the failing asserts commented out).
[fix_the_test.zip](https://github.com/bjoernQ/unmock-plugin/files/275813/fix_the_test.zip)

**Comment by bjoernQ** [comment]
So closing this issue now.

**Comment by rekire** [comment]
Thank you for fixing that. I didn't want to publish my try of the workaround. That was an accident to be honest. However it works now.
My point about a possible bug is just that the other calls seems to work fine out of the box just the float is making trouble.

**Comment by bjoernQ** [comment]
Agree to the last point. Will address this in a future version.

rekire <notifications@github.com> schrieb am Sa., 21. Mai 2016, 12:22:

**Comment by bjoernQ** [comment]
This improvement is now available in 0.5.0
